### ISSUE TITLE
Update ArcDPS Plugins automatically?

### ISSUE THREAD

**Issue by Dagda47** [RaidcoreGG/Nexus#58]
I can't figure out how to start the update process for ArcDPS plugins. In my case "Buddy" and "Healing Stats" each have a message on screen, informing me about an outdated version.

Is it possible for nexus to update these plugins? I don't know how.

**Comment by DeltaGW2** [comment]
The messages shown to you are from the plugins themselves.
Nexus has no information about these addons and therefore cannot provide functionality such as auto-updates or hot-loading as described in the tooltip about the ArcDPS plugin section.
![image](https://github.com/user-attachments/assets/4b87cd9c-7d7b-428c-8a5e-cd355ae34b77)

However, most of them show you an update prompt and can be updated via the same prompt.

The ArcDPS plugins are only listed as means of making it easier for a user to install everything from within the game rather than having to scout for files across the internet.

**Comment by Dagda47** [comment]
Ah, okay . I did hover over the refresh-arrows on the right site but not on the tab itself.

Wasn't the other gw addon manager (GW2-UOAOM) able to update those plugins?

Anyway. Thank you for nexus and your fast response!

**Comment by DeltaGW2** [comment]
UOAOM hardcodes the URLs to be able to update them.
I've been wanting to add support for this too, for the time being given that most ArcDPS plugins are either no longer being developed or simply aren't adding support for Nexus. This will be added at some point, but is currently not a priority.

**Comment by Dagda47** [comment]
I was wondering, why you refered to them as "legacy". Thanks for the explanation.

**Comment by DeltaGW2** [comment]
I'm closing this for now, but as I said proper management of arc plugins is tracked as a planned feature.
